### ISSUE TITLE
Aviso al cambiar de usuario

### ISSUE THREAD

**Issue by excitecube** [hexdump2002/game-miner-public#73]
Si intentas cambiar de usuario y seleccionas otra vez el que tienes actualmente debería salír aviso de que ya tienes ese ahora mismo.

**Comment by hexdump2002** [comment]
Lo que dices es lo correcto pero no lo voy a hacer, como está aún no siendo lo perfecto sigue el flow de usuario de forma normal y hay muchas cosas para hacer.
