### ISSUE TITLE
Save games exporter

### ISSUE THREAD

**Issue by XargonWan** [hexdump2002/game-miner-public#84]
First, sorry if this was already been discussed but I'm not fluent in Spanish.

I wish to have a tool for exporting, or backupping the save states for the non-Steam games.
This tool should be launched automatically when a game is removed from the library.

There could be a default folder in ~/somewhere where the saves are stored.
This behavior may be enabled by default in the settings.

**Comment by hexdump2002** [comment]
This is not possible. Every game works that on its own.
